# Generated by Django 5.0.4 on 2024-05-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='nama',
            new_name='name',
        ),
    ]
