# Generated by Django 5.0.4 on 2024-05-12 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_stockmoves_location_dest_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='stockmoves',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='stockquantity',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='stockquantity',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='stockmoves',
            name='location_dest_id',
        ),
        migrations.RemoveField(
            model_name='stockmoves',
            name='location_id',
        ),
        migrations.AddField(
            model_name='stockmoves',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='polls.locations'),
        ),
        migrations.AddField(
            model_name='stockmoves',
            name='location_dest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_dest', to='polls.locations'),
        ),
    ]
