# Generated by Django 5.0.4 on 2024-05-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, through='polls.StockQuantity', to='polls.products'),
        ),
    ]
