# Generated by Django 5.0.4 on 2024-05-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_locations_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='products',
        ),
    ]
